version: '3.6'  # 使用 Docker Compose 版本 3.6

services:
  gitlab:
    image: gitlab/gitlab-ce:latest    # 使用 GitLab 社群版的最新映像檔    
    container_name: gitlab            # 指定容器名稱為 gitlab
    restart: always                   # 若容器異常停止，自動重啟
    hostname: gitlab.samcheng.home    # 設定容器內部的主機名稱

    environment:
      GITLAB_OMNIBUS_CONFIG: |        
        external_url 'http://gitlab.samcheng.home:8880'        
        gitlab_rails['gitlab_shell_ssh_port'] = 8022
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.gmail.com"
        gitlab_rails['smtp_port'] = 587
        gitlab_rails['smtp_user_name'] = ${smtp_user_name}
        gitlab_rails['smtp_password'] = ${smtp_password}
        gitlab_rails['smtp_domain'] = "gmail.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_email_from'] = "gitlab-home@gmail.com"

    ports:
      - "8880:8880"  # 對外開放 HTTP Web 介面的連接埠
      - "8443:8443"  # 對外開放 HTTPS（未設定 SSL 時可忽略）
      - "8022:8022"  # 對外開放 GitLab SSH 存取 Git 倉庫

    volumes:
      - ./data/config:/etc/gitlab        # 設定檔掛載點
      - ./data/logs:/var/log/gitlab      # 日誌檔掛載點
      - ./data/data:/var/opt/gitlab      # Git 倉庫、資料庫等資料位置

    shm_size: '256m'  # 共享記憶體大小，建議至少設為 256MB 以避免 Git 操作失敗
