{{- if .Values.persistence.enabled }}  # 如果啟用持久化儲存
# n8n 持久化儲存聲明 (PVC) - 用於保存 n8n 工作流程和資料
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "n8n.fullname" . }}-storage
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  accessModes:  # 存取模式
    - {{ .Values.persistence.accessMode }}  # 通常為 ReadWriteOnce
  {{- if .Values.persistence.storageClass }}  # 如果指定儲存類別
  storageClassName: {{ .Values.persistence.storageClass }}  # 儲存類別名稱
  {{- end }}
  resources:  # 資源需求
    requests:
      storage: {{ .Values.persistence.size }}  # 儲存空間大小
{{- end }}  # 結束持久化儲存條件